#!/usr/bin/env python3
"""Script launcher and function exports for MATE v3.0.

Implementation lives in the mate package. Functions are also available here;
new code should import from the relevant mate module.
"""

from mate.cli import get_args as get_args, run
from mate.clustering import (
    perform_clustering_and_extract_ids as perform_clustering_and_extract_ids,
)
from mate.continuous import (
    _bootstrap_continuous_curve as _bootstrap_continuous_curve,
    _bootstrap_pseudotime_curve as _bootstrap_pseudotime_curve,
    _fit_continuous_curve as _fit_continuous_curve,
    _make_continuous_grids as _make_continuous_grids,
    _response_from_replicates as _response_from_replicates,
    _select_continuous_model as _select_continuous_model,
    _trajectory_response_threshold as _trajectory_response_threshold,
    build_continuous_trajectories as build_continuous_trajectories,
)
from mate.embeddings import (
    add_embedding_annotations as add_embedding_annotations,
    get_fingerprint_numeric_columns as get_fingerprint_numeric_columns,
    joint_fingerprint_numeric_columns as joint_fingerprint_numeric_columns,
    pca_on_fingerprints as pca_on_fingerprints,
    prepare_continuous_embedding_table as prepare_continuous_embedding_table,
    prepare_embedding_matrix as prepare_embedding_matrix,
    prepare_joint_embedding_matrix as prepare_joint_embedding_matrix,
    prepare_joint_fingerprint_table as prepare_joint_fingerprint_table,
    run_embedding as run_embedding,
    run_joint_embedding as run_joint_embedding,
    run_trajectory_pca as run_trajectory_pca,
)
from mate.fingerprints import (
    build_feature_lookup as build_feature_lookup,
    calc_metafingerprint as calc_metafingerprint,
    calculate_fingerprints_by_group as calculate_fingerprints_by_group,
    calculate_fingerprints_for_matrix as calculate_fingerprints_for_matrix,
    calculate_sigma as calculate_sigma,
    combine_groups as combine_groups,
    extract_cluster_matrix as extract_cluster_matrix,
    prefix_module_ids as prefix_module_ids,
)
from mate.integration import (
    merge_coherence_into_descriptors as merge_coherence_into_descriptors,
    module_member_coherence as module_member_coherence,
    module_member_coherence_pseudotime as module_member_coherence_pseudotime,
    shared_pattern_tables as shared_pattern_tables,
)
from mate.io import (
    common_sample_columns as common_sample_columns,
    get_group_column as get_group_column,
    group_samples as group_samples,
    load_clusters as load_clusters,
    normalize_feature_table as normalize_feature_table,
    parse_members as parse_members,
    read_feature_table as read_feature_table,
    read_metadata as read_metadata,
)
from mate.lag import (
    _aligned_indices as _aligned_indices,
    _continuous_profiles as _continuous_profiles,
    _continuous_shift_similarity as _continuous_shift_similarity,
    _lag_similarity as _lag_similarity,
    _lag_time_value as _lag_time_value,
    _normalize_profile_for_lag as _normalize_profile_for_lag,
    continuous_cross_omics_lag_analysis as continuous_cross_omics_lag_analysis,
    cross_omics_lag_analysis as cross_omics_lag_analysis,
)
from mate.pipeline import main as main, run_dual_omics_mode as run_dual_omics_mode
from mate.plotting import (
    plot_continuous_lag_pair_diagnostics as plot_continuous_lag_pair_diagnostics,
    plot_embedding as plot_embedding,
    plot_joint_embedding as plot_joint_embedding,
    plot_lag_pair_diagnostics as plot_lag_pair_diagnostics,
    plot_pca as plot_pca,
    plot_trajectory_module_counts as plot_trajectory_module_counts,
    plot_trajectory_profiles as plot_trajectory_profiles,
)
from mate.statistics import (
    _permanova_pseudo_f as _permanova_pseudo_f,
    run_granger_directionality as run_granger_directionality,
    trajectory_separation_statistics as trajectory_separation_statistics,
)
from mate.trajectories import (
    _numeric_times as _numeric_times,
    calculate_pseudotime_trajectory_descriptors as calculate_pseudotime_trajectory_descriptors,
    calculate_trajectory_descriptors as calculate_trajectory_descriptors,
    condition_time_sample_groups as condition_time_sample_groups,
    descriptor_profile_matrix as descriptor_profile_matrix,
    fingerprint_sample_columns as fingerprint_sample_columns,
    get_trajectory_time_columns as get_trajectory_time_columns,
    resolve_stratify_column as resolve_stratify_column,
    resolve_time_column as resolve_time_column,
    resolve_time_values as resolve_time_values,
    response_timing_label as response_timing_label,
    standardized_mean_difference as standardized_mean_difference,
    time_sample_groups as time_sample_groups,
    timepoint_means_for_row as timepoint_means_for_row,
    trajectory_time_labels as trajectory_time_labels,
    transition_label as transition_label,
    transition_label_metric as transition_label_metric,
)
from mate.utils import (
    find_column as find_column,
    natural_key as natural_key,
    orient_vector as orient_vector,
    parse_comma_list as parse_comma_list,
    safe_output_prefix as safe_output_prefix,
)

__all__ = [
    "_aligned_indices",
    "_bootstrap_continuous_curve",
    "_bootstrap_pseudotime_curve",
    "_continuous_profiles",
    "_continuous_shift_similarity",
    "_fit_continuous_curve",
    "_lag_similarity",
    "_lag_time_value",
    "_make_continuous_grids",
    "_normalize_profile_for_lag",
    "_numeric_times",
    "_permanova_pseudo_f",
    "_response_from_replicates",
    "_select_continuous_model",
    "_trajectory_response_threshold",
    "add_embedding_annotations",
    "build_continuous_trajectories",
    "build_feature_lookup",
    "calc_metafingerprint",
    "calculate_fingerprints_by_group",
    "calculate_fingerprints_for_matrix",
    "calculate_pseudotime_trajectory_descriptors",
    "calculate_sigma",
    "calculate_trajectory_descriptors",
    "combine_groups",
    "common_sample_columns",
    "condition_time_sample_groups",
    "continuous_cross_omics_lag_analysis",
    "cross_omics_lag_analysis",
    "descriptor_profile_matrix",
    "extract_cluster_matrix",
    "find_column",
    "fingerprint_sample_columns",
    "get_args",
    "get_fingerprint_numeric_columns",
    "get_group_column",
    "get_trajectory_time_columns",
    "group_samples",
    "joint_fingerprint_numeric_columns",
    "load_clusters",
    "main",
    "merge_coherence_into_descriptors",
    "module_member_coherence",
    "module_member_coherence_pseudotime",
    "natural_key",
    "normalize_feature_table",
    "orient_vector",
    "parse_comma_list",
    "parse_members",
    "pca_on_fingerprints",
    "perform_clustering_and_extract_ids",
    "plot_continuous_lag_pair_diagnostics",
    "plot_embedding",
    "plot_joint_embedding",
    "plot_lag_pair_diagnostics",
    "plot_pca",
    "plot_trajectory_module_counts",
    "plot_trajectory_profiles",
    "prefix_module_ids",
    "prepare_continuous_embedding_table",
    "prepare_embedding_matrix",
    "prepare_joint_embedding_matrix",
    "prepare_joint_fingerprint_table",
    "read_feature_table",
    "read_metadata",
    "resolve_stratify_column",
    "resolve_time_column",
    "resolve_time_values",
    "response_timing_label",
    "run",
    "run_dual_omics_mode",
    "run_embedding",
    "run_granger_directionality",
    "run_joint_embedding",
    "run_trajectory_pca",
    "safe_output_prefix",
    "shared_pattern_tables",
    "standardized_mean_difference",
    "time_sample_groups",
    "timepoint_means_for_row",
    "trajectory_separation_statistics",
    "trajectory_time_labels",
    "transition_label",
    "transition_label_metric",
]


if __name__ == "__main__":
    run()
